### PR TITLE
Valgrind upgrade and bugfix

### PR DESCRIPTION
**Pull request by esben**
Upgrade valgrind to 3.10.1 and fix compatibility with glibc 2.21 so we are able to upgrade toolchain.

### CODE REVIEW

**Comment by kimrhh** [comment]
could we retest this against master?

**Comment by esben** [comment]
I have merged the toolchain upgrade to OE-lite/core, which should fix this PR.

**Comment by esben** [comment]
There you go, it builds fine with recent gcc and glibc :smiley:

**Comment by kimrhh** [comment]
merged, thanks!

**Comment by esben** [comment]
I always look at the SRC_URI to determine what is being used in a recipe.  Anything else is (like guessing based on files in the recipe dir) is flawed when taking into consideration the way the OE-lite work.  There might be patches left there which are not referred to anymore (these should of-course be removed/cleaned up), and patches could be applied conditionally (not generally a a good idea IMHO, but it is possible and is done in several places).

**Pull request merged**
