### PR TITLE
gtk-doc: Add machine recipe type

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by diorcety** [comment]
Hi,

It's needed by some gtk recipes from gtk meta

Regards,

**Comment by esben** [comment]
Is it possible that the recipes needing this are using "gtk-doc" in DEPENDS, where they could just as well use "host-cross:gtk-doc" instead?

**Comment by diorcety** [comment]
Yes maybe that the solution. But actually gtk-doc containing only a m4 (referencing a pkg-config file from somewhere???) That could lead to issues on computer without gtk-doc installed.

**Comment by esben** [comment]
Uh, you are right.  That definitely does sound bad.

**Comment by kimrhh** [comment]
fixed in PR #14

**Pull request closed without merging**
