### PR TITLE
Wget improvements

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by esben** [comment]
LGTM (although patch headers does not have upstream status field).

**Comment by kimrhh** [comment]
would be really nice to know if those patches have been accepted upstream.

**Comment by esben** [comment]
@diorcety will you update this PR with upstream status of both patches?

**Comment by esben** [comment]
This is now 5 months pending. Could we please merge this?

**Comment by kimrhh** [comment]
i had not noticed the patch headers were updated, sure I will merge it

**Comment by kimrhh** [comment]
merged, thanks!

**Pull request merged**
