### PR TITLE
busybox: Add USE flag to enable '-o loop' support in mount command

### PR DESCRIPTION
**Pull request by esben**
Signed-off-by: Esben Haabendal <esben@haabendal.dk>

### CODE REVIEW

**Comment by kimrhh** [comment]
looks good, but I'm wondering why we are make all these things so extremely configurable. If this feature where to pull in a huge dependency or something I might understand it, but why not just make this hard enabled by default and then let someone who might need to make a system without it deal with fixing that?

**Comment by kimrhh** [comment]
to be clear, I see nothing wrong with this change (if the option is enabled by default?), but where should we open discussions like this?

**Comment by esben** [comment]
The PR currently does not enable the feature by default.  Should I update with that changed?

As for the general discussion about busybox configurability in OE-lite, I also don't think the current state in OE-lite is ideal. But it clearly (the discussion) belongs somewhere else than in this PR :)

**Comment by kimrhh** [comment]
my personal opinion would be that such a feature should be enabled by default, since that would be what most people would expect from a normal system, so if you don't mind please do that :) I'll start up some issues to discuss some larger things regarding busybox

**Comment by esben** [comment]
I put the enable by default in separate commit, so the first commit can be cherry-picked to old releases without breaking full backwards compatibility.

**Comment by kimrhh** [comment]
oh right, great! thanks

**Pull request merged**
