### PR TITLE
libwebsockets: add recipe

### PR DESCRIPTION
**Pull request by Villemoes**

### CODE REVIEW

**Comment by kimrhh** [comment]
how does this relate to the libwebsockets recipe in #345 ? can we just drop that since this is newer?

**Comment by kimrhh** [comment]
hm, this recipe is not as finished as the other one. please port over the auto-package stuff etc.

**Comment by Villemoes** [comment]
Done.

**Comment by kimrhh** [comment]
LGTM, just need a COMPATIBLE_HOST_ARCHS = ".*linux"

**Pull request merged**
