### PR TITLE
u-boot-tools: Support FIT image creation

### PR DESCRIPTION
**Pull request by esben**
Signed-off-by: Esben Haabendal <esben@haabendal.dk>

### CODE REVIEW

**Comment by kimrhh** [comment]
do we maybe need to handle this via a flag? thinking for systems that do not have dtc available

**Comment by esben** [comment]
We could do that if you want.
But as we are only doing this for native and sdk, it probably does not matter much.
The dtc binary is less than 80k big, and takes less than 10 seconds to build (all steps) on my laptop.

**Comment by kimrhh** [comment]
oh i see we can always build dtc, fine then

**Comment by kimrhh** [comment]
merged, thanks

**Pull request merged**
