### PR TITLE
libevdev: New recipe (rebase of commits from madsdore)

### PR DESCRIPTION
**Pull request by esben**
This PR is a squash and rebase of PR #5.

### CODE REVIEW

**Comment by kimrhh** [comment]
is there a reason for adding this to base? I would say it belongs in meta/xorg

**Comment by esben** [comment]
Maybe.  I just rebased the old PR.

For now, I guess it will only be used with X.org.  But won't it also be useful together with libinput and weston/wayland?  And in that case, where would be place recipes used by both X and wayland ?

**Comment by kimrhh** [comment]
without checking, I would think we have other such things i meta/xorg already. I think we should defer a fix for wayland until we get someone willing to add it? Then we could make a meta/freedesktop or something with the shared stuff. IMO we should try to not just add stuff to base because we can't come up with a better place

**Comment by esben** [comment]
Fair enough.

**Comment by esben** [comment]
PR created on xorg.

**Pull request closed without merging**
