### PR TITLE
Curl upgrade

### PR DESCRIPTION
**Pull request by esben**

### CODE REVIEW

**Comment by esben** [comment]
Hmm... Should I resubmit this against next branch?  I don't seem to be able to change the branch target after creating the PR.

**Comment by kimrhh** [comment]
I will just merge it to master when the 4.0.0 release has been done

**Comment by esben** [comment]
Unless 4.0.0 release is very close, I hope you will consider opening up a 4.x release branch (or something like that), so we can get things such as this merged.

**Comment by esben** [comment]
Ready for merge :)

**Comment by kimrhh** [comment]
merged, thanks

**Pull request merged**
