### PR TITLE
imx-usb-loader

### PR DESCRIPTION
**Pull request by moths**
libusb1 and usbutils fixes, for building imx-usb-loader (meta/fsl) for sdk

### CODE REVIEW

**Comment by kimrhh** [comment]
i just poked our meta/fsl maintainer to get that repo to a state where we can start submitting. I think that will happen soon, so I will leave this PR open for now in the hope we can move it there soon :)

**Comment by kimrhh** [comment]
could you move this to the meta/fsl repo?

**Comment by moths** [comment]
Moved imx-usb-loader to meta/fsl, now the two usb commits are needed in base for it to work.

**Comment by kimrhh** [comment]
great, thanks!

**Pull request merged**
