### PR TITLE
Rsyslog libdbi

### PR DESCRIPTION
**Pull request by sknsean**

### CODE REVIEW

**Comment by kimrhh** [comment]
please re-submit with only the libdbi stuff, since the rest has been merged in other PRs

**Comment by esben** [comment]
@sknsean you didn't have to close the PR, you could just have done a non-fastforward push of the rebased branch to sknsean:rsyslog-libdbi and this PR would have been ready to be merged.

**Comment by sknsean** [comment]
Oh, I see... I should have done this the other way around :-)

**Comment by esben** [comment]
I am sure you will get a new chance to try it in the future :smiley:

**Pull request closed without merging**
