### PR TITLE
Libevent tmux vim

### PR DESCRIPTION
**Pull request by ksorensen**
Resubmit pull request

  - Changed Vim license to "Vim"
  - Added HOMEPAGE to Vim recipe
  - Removed unnecessary creation of sysconfdir

### CODE REVIEW

**Comment by esben** [comment]
LGTM :+1:

**Comment by esben** [comment]
Mingw build should be fixed, or COMPATIBLE_HOST_ARCHS set to avoid building for mingw hosts.
I guess the last option is good enough, and quick to do :)

    COMPATIBLE_HOST_ARCHS = ".*linux"

**Comment by ksorensen** [comment]
I'll add it and force push

**Comment by kimrhh** [comment]
nice! :+1: , will merge when the mingw build is skipped.

**Comment by esben** [comment]
Yes, tmux needs to be linux-only also.

**Comment by ksorensen** [comment]
added

COMPATIBLE_HOST_ARCHS = ".*linux"

to tmux recipe and removed unnecessary temporary commented out line from vim recipe.

I assume libevent is ok for cygwin since it only depends on libm.

**Comment by kimrhh** [comment]
merged, thanks!

**Pull request merged**
