### PR TITLE
wpa-supplicant: add version 2.5

### PR DESCRIPTION
**Pull request by sknsean**

### CODE REVIEW

**Comment by kimrhh** [comment]
please base this on PR #209

**Comment by sknsean** [comment]
In the history there seems to be no explanation to why we default are using gnutls?
Default in wpa_supplicant is openssl...
Should we change this?

**Comment by kimrhh** [comment]
probably because only gnutls was available on the target this recipe was originially created for :)

You can make it possible to use either if you prefer openssl, but don't just change to another hardcoded default.

**Comment by kimrhh** [comment]
this PR replaces PR #209

**Comment by kimrhh** [comment]
i'll merge this now, then you can add openssl support in an additional PR :)

**Pull request merged**
